name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: door-interface

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      
      - name: Log into registry
        run: echo ${{secrets.DOORINTBUILD_DOCKER_PASSWORD}} | docker login docker.richardjameskendall.com -u doorintbuild --password-stdin
      
      - name: Build image
        run: docker buildx build --platform linux/arm/v7 --output "type=image,push=true" --file Dockerfile -t docker.richardjameskendall.com/door-interface .
